const barrels = [
	[
		"ArmCom Assault Barrel",
		"Briar Accuracy Barrel",
		"Briar Assault Barrel",
		"Briar Balanced Barrel",
		"Briar CQC Barrel",
		"Briar Lightweight Barrel",
		"Frontier Compensator Barrel",
		"Frontier Standard Barrel",
		"Krane Assault Barrel",
		"Krane Heavy Assault Barrel",
		"Leatherneck Accuracy Barrel",
		"Ogre CQC Barrel",
		"Prestige Frontier Standard Barrel",
		"Raider Snub Barrel",
		"Redsand CQC Barrel",
		"Silverwood CQC Barrel",
		"Silverwood Light Accuracy Barrel",
		"Silverwood SW-09",
		"Titan Assault Barrel",
		"Titan Extended Barrel",
	],
	["Overmatch A-12 Blast", "Overmatch Heavy X3", "Overmatch CRC-7 Post"],
	["Titan FFB", "Overmatch M-CV Breach", "Krane SG Bar-20"],
	[
		"Armcom BAR-01",
		"Armcom BARl1",
		"Briar BAR Grip",
		"Briar BAR-02",
		"Hullbreach 047BAR",
		"Hullbreach 057BAR",
		"Silverwood TechBAR",
		"No Grip",
	],
	["No Barrel Mod", "V2 X200 Mod", "V2 Z900 Mod"],
	["No Barrel Mod"],
];

const grips = [[], ["Briar BrGR1", "Briar BrSGP1"]];

const stocks = [
	[
		"Redsand Compensator Stock",
		"Prestige Silverwood Standard Stock",
		"ArmCom Folding Stock",
		"Overmatch Compensator Stock",
		"Silverwood Standard Stock",
		"Hullbreach CQC Stock",
		"Krane Tactical Stock",
		"Taurex Stabilizing Stock",
		"Silverwood Compensator Stock",
		"V2 Folding Stock",
		"Vulcan Extender Stock",
		"Krane Extender Stock",
		"ArmCom Compensator Stock",
		"Krane Ultralight Stock",
		"Frontier Ultralight Stock",
		"No Stock",
	],
	[
		"Silverwood z1200 BPFA",
		"Hullbreach 89-BPFA",
		"Briar Elite A4-BS",
		"MMRS BP-CQ + PCR",
		"MMRS BP-XLi",
		"MMRS BP-SR Tactical",
	],
	["No Stock"],
];

const muzzles = [
	{
		None: "0",
	},
	{
		"ArmCom Slit Flash breaker": "1",
		"Nexus Extended Range Muzzle": "2",
		"Frontier Standard Suppressor": "3",
		"Briar Dampening Muzzle": "4",
		"Vulcan Notched Flash breaker": "5",
		"Briar Enhanced Suppressor": "6",
		"Vulcan Compensator": "7",
		"Vulcan Longreach Flash breaker": "8",
		"Overmatch Muzzle Shroud": "9",
		"ArmCom Enhanced Suppressor": "10",
		"Frontier Power Muzzle": "11",
		"Silverwood Flash breaker": "12",
		"Vulcan Power Brake": "13",
		"Krane Power Muzzle": "14",
		"Briar Extender Muzzle": "15",
		"ArmCom Power Muzzle": "16",
		"ArmCom Balanced Muzzle": "17",
		Gold: "18",
	},
];
muzzles[2] = { ...muzzles[0], ...muzzles[1] };

const scopes = [
	"4X Ammo Counter Scope",
	"Aim Point Ammo Counter",
	"ArmCom CQC Scope",
	"ArmCom Infrared Scope",
	"ArmCom Sniper Scope",
	"EMI ACOG Scope",
	"EMI Electric Scope",
	"EMI Infrared Scope",
	"EMI Infrared Scope Mk. 2",
	"EMI Tech Scope",
	"EON Electric Scope",
	"Frontier Sniper Scope",
	"invalid scope",
	"Krane Holo Sight",
	"Krane Sniper Scope",
	"Krane Tactical Scope",
	"Lightsky Red Dot Sight",
	"Lightsky Reflex Sight",
	"MMRS Flip-Up Rail Sight",
	"No Optic Mod",
	"OPRL Holo Sight",
	"Prestige Titan Rail Sight",
	"Silverwood Combo Scope",
	"Silverwood Heavy Scope",
	"Titan Rail Sight",
];

const primary = {
	"AK470 Rifle": {
		ammo: {
			Standard: "195",
			Light: "196",
			Quick: "197",
			Extended: "198",
			Express: "199",
			Electro: "200",
			Explosive: "201",
			Incendiary: "202",
			Toxic: "203",
			Magnum: "204",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Anti-Materiel Rifle": {
		ammo: {
			Standard: "90",
			Light: "91",
			Quick: "92",
			Extended: "93",
			Express: "94",
			Electro: "95",
			Explosive: "96",
			Incendiary: "97",
			Toxic: "98",
			Magnum: "165",
		},
		barrels: barrels[5],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[0],
	},
	"Assault Rifle": {
		ammo: {
			Standard: "9",
			Light: "10",
			Quick: "11",
			Extended: "12",
			Express: "13",
			Drummed: "14",
			Relentless: "15",
			Electro: "16",
			Explosive: "17",
			Incendiary: "18",
			Toxic: "19",
			Magnum: "160",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Bolt-Action Rifle": {
		ammo: {
			Standard: "90",
			Light: "91",
			Quick: "92",
			Extended: "93",
			Express: "94",
			Electro: "95",
			Explosive: "96",
			Incendiary: "97",
			Toxic: "98",
			Magnum: "165",
		},
		barrels: barrels[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Bullpup Full Auto": {
		ammo: {
			Standard: "149",
			Light: "150",
			Quick: "151",
			Extended: "152",
			Express: "153",
			Electro: "154",
			Explosive: "155",
			Incendiary: "156",
			Toxic: "157",
			Magnum: "163",
		},
		barrels: barrels[3],
		stocks: stocks[1],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Burstfire Rifle": {
		ammo: {
			Standard: "81",
			Light: "82",
			Quick: "83",
			Extended: "84",
			Express: "85",
			Electro: "86",
			Explosive: "87",
			Incendiary: "88",
			Toxic: "89",
			Magnum: "161",
		},
		barrels: barrels[0],
		stocks: stocks[1],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Burstfire SMG": {
		ammo: {
			Standard: "140",
			Light: "141",
			Quick: "142",
			Extended: "143",
			Express: "144",
			Electro: "145",
			Explosive: "146",
			Incendiary: "147",
			Toxic: "148",
			Magnum: "159",
		},
		barrels: barrels[5],
		stocks: stocks[2],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Combat Rifle": {
		ammo: {
			Standard: "20",
			Light: "21",
			Quick: "22",
			Extended: "23",
			Express: "24",
			Electro: "25",
			Explosive: "26",
			Incendiary: "27",
			Toxic: "28",
			Magnum: "164",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Compound Bow": {
		ammo: {
			Standard: "205",
			Explosive: "206",
			Stun: "207",
			Poison: "208",
			Light: "209",
			Heavy: "210",
			Cupid: "211",
		},
		barrels: barrels[5],
		stocks: stocks[2],
		grips: grips[0],
		muzzles: muzzles[0],
	},
	"Heavy Assault Rifle": {
		ammo: {
			Standard: "115",
			Light: "116",
			Quick: "117",
			Extended: "118",
			Express: "119",
			Electro: "120",
			Explosive: "121",
			Incendiary: "122",
			Toxic: "123",
			Magnum: "162",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Light Machine Gun": {
		ammo: {
			Standard: "39",
			Quick: "40",
			Electro: "41",
			Explosive: "42",
			Incendiary: "43",
			Toxic: "44",
			Magnum: "168",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Light Recon Rifle": {
		ammo: {
			Standard: "212",
			Light: "213",
			Quick: "214",
			Extended: "215",
			Express: "216",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"LMG Recon": {
		ammo: {
			Standard: "104",
			Light: "105",
			Heavy: "106",
			Electro: "136",
			Explosive: "137",
			Incendiary: "138",
			Toxic: "139",
			Magnum: "175",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"M4X Rifle": {
		ammo: {
			Standard: "185",
			Light: "186",
			Quick: "187",
			Extended: "188",
			Express: "189",
			Electro: "190",
			Explosive: "191",
			Incendiary: "192",
			Toxic: "193",
			Magnum: "194",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	None: {
		ammo: {
			Standard: "9",
		},
		barrels: barrels[5],
		stocks: stocks[2],
		grips: grips[0],
		muzzles: muzzles[0],
	},
	"Prestige Assault Rifle": {
		ammo: {
			Standard: "9",
			Light: "10",
			Quick: "11",
			Extended: "12",
			Express: "13",
			Drummed: "14",
			Relentless: "15",
			Electro: "16",
			Explosive: "17",
			Incendiary: "18",
			Toxic: "19",
			Magnum: "160",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Submachine Gun": {
		ammo: {
			Standard: "0",
			Light: "1",
			Quick: "2",
			Extended: "3",
			Express: "4",
			Electro: "5",
			Explosive: "6",
			Incendiary: "7",
			Toxic: "8",
			Magnum: "158",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Tactical Assault Rifle": {
		ammo: {
			Standard: "9",
			Light: "10",
			Quick: "11",
			Extended: "12",
			Express: "13",
			Drummed: "14",
			Relentless: "15",
			Electro: "16",
			Explosive: "17",
			Incendiary: "18",
			Toxic: "19",
			Magnum: "160",
		},
		barrels: barrels[0],
		stocks: stocks[0],
		grips: grips[0],
		muzzles: muzzles[1],
	},
	"Tactical SMG": {
		ammo: {
			Standard: "107",
			Light: "108",
			Quick: "109",
			Extended: "110",
			Electro: "111",
			Explosive: "112",
			Incendiary: "113",
			Toxic: "114",
			Magnum: "174",
		},
		barrels: barrels[5],
		stocks: stocks[2],
		grips: grips[0],
		muzzles: muzzles[1],
	},
};

const secondary = {
	"Breech Loaded Pistol": {
		ammo: { Explosive: "134", Incendiary: "135", Scattershot: "176" },
		grips: grips[0],
		barrels: barrels[5],
		stocks: stocks[2],
		muzzles: muzzles[0],
	},
	"Burstfire Pistol": {
		ammo: {
			Standard: "72",
			Light: "73",
			Quick: "74",
			Extended: "75",
			Express: "76",
			Electro: "77",
			Explosive: "78",
			Incendiary: "79",
			Toxic: "80",
			Magnum: "172",
		},
		grips: grips[0],
		barrels: barrels[5],
		stocks: stocks[2],
		muzzles: muzzles[2],
	},
	"Heavy Pistol": {
		ammo: {
			Standard: "45",
			Light: "46",
			Quick: "47",
			Extended: "48",
			Express: "49",
			Electro: "50",
			Explosive: "51",
			Incendiary: "52",
			Toxic: "53",
			Magnum: "169",
		},
		grips: grips[0],
		barrels: barrels[4],
		stocks: stocks[2],
		muzzles: muzzles[2],
	},
	"Light Pistol": {
		ammo: {
			Standard: "54",
			Light: "55",
			Quick: "56",
			Extended: "57",
			Express: "58",
			Electro: "59",
			Explosive: "60",
			Incendiary: "61",
			Toxic: "62",
			Magnum: "170",
		},
		grips: grips[0],
		barrels: barrels[4],
		stocks: stocks[2],
		muzzles: muzzles[2],
	},
	"Machine Pistol": {
		ammo: {
			Standard: "63",
			Light: "64",
			Quick: "65",
			Extended: "66",
			Express: "67",
			Electro: "68",
			Explosive: "69",
			Incendiary: "70",
			Toxic: "71",
			Magnum: "171",
		},
		grips: grips[0],
		barrels: barrels[5],
		stocks: stocks[2],
		muzzles: muzzles[2],
	},
	None: {
		ammo: { Standard: "9" },
		grips: grips[0],
		barrels: barrels[5],
		stocks: stocks[2],
		muzzles: muzzles[0],
	},
	"Prestige Light Pistol": {
		ammo: {
			Standard: "54",
			Light: "55",
			Quick: "56",
			Extended: "57",
			Express: "58",
			Electro: "59",
			Explosive: "60",
			Incendiary: "61",
			Toxic: "62",
			Magnum: "170",
		},
		grips: grips[0],
		barrels: barrels[4],
		stocks: stocks[2],
		muzzles: muzzles[2],
	},
	Revolver: {
		ammo: {
			Standard: "99",
			Electro: "100",
			Explosive: "101",
			Incendiary: "102",
			Toxic: "103",
			Magnum: "173",
		},
		grips: grips[0],
		barrels: barrels[5],
		stocks: stocks[2],
		muzzles: muzzles[0],
	},
	Shotgun: {
		ammo: {
			Standard: "29",
			Light: "30",
			Quick: "31",
			Extended: "32",
			Express: "33",
			Drummed: "34",
			Electro: "35",
			Explosive: "36",
			Incendiary: "37",
			Toxic: "38",
			Magnum: "166",
		},
		grips: grips[1],
		barrels: barrels[2],
		stocks: stocks[0],
		muzzles: muzzles[0],
	},
	"Shotgun AR-k": {
		ammo: {
			Standard: "124",
			Light: "125",
			Quick: "126",
			Extended: "127",
			Express: "128",
			Electro: "129",
			Explosive: "130",
			Incendiary: "131",
			Toxic: "132",
			Drummed: "133",
			Magnum: "167",
		},
		grips: grips[0],
		barrels: barrels[1],
		stocks: stocks[0],
		muzzles: muzzles[0],
	},
	"Snub 260": {
		ammo: {
			Standard: "177",
			Precision: "178",
			Caliber: "179",
			Incendiary: "180",
			Electro: "181",
			Explosive: "182",
			Toxic: "183",
			Magnum: "184",
		},
		grips: grips[0],
		barrels: barrels[5],
		stocks: stocks[2],
		muzzles: muzzles[0],
	},
};

const gear = {
	"No Gear": "0",
	"Frag Grenade Mk.1": "1",
	"Combat Knife Mk.1": "2",
	"Shock Grenade Mk.1": "3",
	"EMP Grenade Mk.1": "4",
	"Digi Grenade Mk.1": "5",
	"Proximity Mine Mk.1": "6",
	"HRV Decoy Mk.1": "7",
	"Stun Mine Mk.1": "8",
	"Toxic Grenade Mk.1": "9",
	"HE Grenade Mk.1": "10",
	"HRV Blackout Mk.1": "11",
	"Combat Knife Mk.2": "12",
	Machete: "13",
	"Breach Hammer": "14",
	"Throwing Knives Mk.1": "15",
	"Black Mesa Crowbar": "16",
	"Golden Crowbar": "17",
	"Silver Crowbar": "18",
	"Exploding Tomahawk": "19",
	"Incendiary Protection Gear": "20",
	"Toxic Protection Gear": "21",
	"Explosive Protection Gear": "22",
	"Electro Protection Gear": "23",
	"Melee Protection Gear": "24",
	"Personal Holo-decoy": "25",
	"Stun Shuriken": "26",
	"Sonic Tomahawk": "27",
	"Infrared Protection Gear": "28",
	"Toxic Breach Hammer": "33",
	"Frag Mk.1 - Lightning Trail Mod": "34",
	"Frag Mk.1 - Lightning Trail and Strike Mod": "35",
	"Frag Mk.1 - Flame Mod": "36",
	"Frag Mk.1 - Fire Mod": "37",
	"Frag Mk.1 - Lightning Strike Mod": "38",
	"Frag Mk.1 - Blue Explosion Mod": "39",
	"Frag Mk.1 - Pink Explosion Mod": "40",
	"Frag Mk.1 - Purple Explosion Mod": "41",
	"Frag Mk.1 - Red Explosion Mod": "42",
	"Frag Mk.1 - Blue and Yellow Explosion Mod": "43",
	"Frag Mk.1 - Blue BOOM Explosion Mod": "44",
	"Frag Mk.1 - Butterfly Mod": "45",
	Snowpocalypse: "46",
	"Tactical Ice Axe": "47",
	"Nor'Easter": "48",
	"Prestige Frag Grenade Mk.1": "49",
	"Prestige Combat Knife Mk.1": "50",
	"I Heart U": "51",
};

const tactical = {
	"No Tactical Gear": "0",
	"Heal Injector Mk.1": "1",
	"Repair Tool": "2",
	"Ammunition Pod Mk.1": "3",
	"Barricade Mk.1": "4",
	"Revival Injector Mk.1": "5",
	Cloak: "6",
	"Hardsuit HRV Ping": "7",
	"Hardsuit Battle Mode": "8",
	"Respawn Beacon": "9",
	"Firewall Breach Kit": "10",
	"HRV Cloak": "11",
	"Cloak Mk.2": "12",
	"Barricade Mk.2": "13",
};

export { scopes, primary, secondary, gear, tactical };
